version: "3.7"

services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: k8s_test

  server:
    image: node:12-alpine
    command: sh -c "cd /server; npm i; npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /server
