name: Server-1

env:
  CI: true

on: push
#     paths:
#       - "server-1/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Build production image
        working-directory: ./server-1
        run: |
          tagName="$GITHUB_REPOSITORY/$GITHUB_WORKFLOW"
          lowercaseTagName="$( echo $tagName | tr '[:upper:]' '[:lower:]' )"
          docker build -f prod.Dockerfile -t "$lowercaseTagName:$GITHUB_RUN_ID" .
          docker tag "$lowercaseTagName:$GITHUB_RUN_ID" "$lowercaseTagName:latest"
